# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24193de3d7837cab554bb1ff8b53d388"
name = "refund"
application_url = "https://refund-ztxz.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_returns,write_returns"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/returns"
  topics = [ "returns/request", "returns/approve", "returns/cancel", "returns/close", "returns/decline", "returns/process", "returns/reopen", "returns/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/refunds"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://refund-ztxz.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
