import express from "express";
import { authorizationHandler } from "@modelcontextprotocol/sdk/server/auth/handlers/authorize.js";
import { tokenHandler } from "@modelcontextprotocol/sdk/server/auth/handlers/token.js";
import { clientRegistrationHandler } from "@modelcontextprotocol/sdk/server/auth/handlers/register.js";
import { revocationHandler } from "@modelcontextprotocol/sdk/server/auth/handlers/revoke.js";
import { metadataHandler } from "@modelcontextprotocol/sdk/server/auth/handlers/metadata.js";
import {
  createAgentOAuthProvider,
  agentOAuthMetadata,
} from "../app/services/agent-oauth-provider.server";
import {
  appOrigin,
  privateHeaders,
} from "../app/services/customer-security.server";

export function createOAuthRouter(provider = createAgentOAuthProvider()) {
  const router = express.Router();
  router.use(
    ["/authorize", "/token", "/register", "/revoke"],
    (req, res, next) => {
      res.set(privateHeaders);
      // Include RFC 9207 issuer identification on every authorization redirect,
      // including validation errors generated by the SDK's authorization handler.
      const redirect = res.redirect.bind(res);
      res.redirect = ((statusOrUrl: number | string, maybeUrl?: string) => {
        const url = new URL(
          typeof statusOrUrl === "string" ? statusOrUrl : maybeUrl!,
          appOrigin(),
        );
        url.searchParams.set("iss", appOrigin());
        return redirect(
          typeof statusOrUrl === "number" ? statusOrUrl : 302,
          url.href,
        );
      }) as typeof res.redirect;
      next();
    },
  );
  // Set limits before the SDK's parsers. Other app routes retain their own body handling.
  router.use(
    ["/authorize", "/token", "/revoke"],
    express.urlencoded({ extended: false, limit: "8kb", parameterLimit: 30 }),
  );
  router.use("/register", express.json({ limit: "8kb" }));
  router.use(
    "/.well-known/oauth-authorization-server",
    metadataHandler(agentOAuthMetadata()),
  );
  router.use("/authorize", authorizationHandler({ provider }));
  router.use("/token", tokenHandler({ provider }));
  router.use(
    "/register",
    clientRegistrationHandler({
      clientsStore: provider.clientsStore,
      clientSecretExpirySeconds: 0,
    }),
  );
  router.use("/revoke", revocationHandler({ provider }));
  return router;
}
